# Generated by Django 5.2.3 on 2025-06-17 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticias_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='TipoJuez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Juez',
                'verbose_name_plural': 'Tipos de Juez',
            },
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='jueces/')),
                ('email', models.EmailField(max_length=254)),
                ('celular1', models.CharField(max_length=20)),
                ('celular2', models.CharField(blank=True, max_length=20, null=True)),
                ('afijo', models.CharField(blank=True, max_length=100, null=True)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('especialidades', models.ManyToManyField(related_name='jueces', to='core.especialidad')),
                ('licencias', models.ManyToManyField(blank=True, related_name='jueces', to='core.licencia')),
                ('razas', models.ManyToManyField(related_name='jueces', to='core.raza')),
                ('tipo_juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipojuez')),
            ],
            options={
                'verbose_name': 'Juez',
                'verbose_name_plural': 'Jueces',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
    ]
