# Generated by Django 5.2.3 on 2025-06-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_especialidad_licencia_raza_tipojuez_juez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juez',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
