# Generated by Django 5.2.3 on 2025-06-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_evento_descripcion_alter_evento_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='invitados',
        ),
        migrations.AddField(
            model_name='evento',
            name='invitados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
