# Generated by Django 5.2.3 on 2025-06-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_evento_invitados_evento_invitados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(help_text='Selecciona mes y año')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='rankings/')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['-fecha'],
            },
        ),
    ]
