# Generated by Django 5.2.3 on 2025-06-19 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='fecha',
            field=models.CharField(help_text='Formato: YYYY-MM (ej: 2024-01 para Enero 2024)', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa la fecha en formato YYYY-MM (ej: 2024-01)', regex='^\\d{4}-\\d{2}$')]),
        ),
    ]
