# Generated by Django 5.2.3 on 2025-06-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ranking_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
