# Generated by Django 5.2.3 on 2025-06-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ranking_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreReglamento', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='reglamentos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reglamento',
                'verbose_name_plural': 'Reglamentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
