# Generated by Django 5.2.3 on 2025-06-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reglamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crianza',
                'verbose_name_plural': 'Crianza',
            },
        ),
    ]
