# Generated by Django 5.2.3 on 2025-06-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_crianza'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaRazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historia de Raza',
                'verbose_name_plural': 'Historias de Razas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoHistoriaRaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='historia_razas/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('historia_raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.historiarazas')),
            ],
            options={
                'verbose_name': 'Foto de Historia de Raza',
                'verbose_name_plural': 'Fotos de Historias de Razas',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
