# Generated by Django 5.2.3 on 2025-06-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historiarazas_fotohistoriaraza'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiarazas',
            name='imagenPrincipal',
            field=models.ImageField(blank=True, null=True, upload_to='historia_razas/'),
        ),
    ]
