# Generated by Django 5.2.3 on 2025-06-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiarazas',
            name='clubes',
            field=models.ManyToManyField(blank=True, related_name='historias_razas', to='core.club'),
        ),
    ]
