# Generated by Django 5.2.3 on 2025-06-22 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_historiarazas_clubes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tramites/')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tramites/archivos/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.tramites')),
            ],
            options={
                'verbose_name': 'Archivo de Trámite',
                'verbose_name_plural': 'Archivos de Trámites',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
