# Generated by Django 5.2.3 on 2025-06-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tramites_archivotramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(choices=[('tramites', 'Trámites y Documentación'), ('cruza', 'Cruza y Camadas'), ('exposiciones', 'Exposiciones y Campeonatos'), ('contacto', 'Contacto y Horarios')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['categoria', 'orden'],
            },
        ),
    ]
