# Generated by Django 5.2.3 on 2025-07-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_convert_to_ckeditor5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivotramite',
            name='archivo',
            field=models.FileField(upload_to='static/files/tramites/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/clubes/'),
        ),
        migrations.AlterField(
            model_name='fotohistoriaraza',
            name='imagen',
            field=models.ImageField(upload_to='static/img/historia_razas/'),
        ),
        migrations.AlterField(
            model_name='historiarazas',
            name='imagenPrincipal',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/historia_razas/'),
        ),
        migrations.AlterField(
            model_name='juez',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='static/files/curriculums/'),
        ),
        migrations.AlterField(
            model_name='juez',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/jueces/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/noticias/'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='static/files/rankings/'),
        ),
        migrations.AlterField(
            model_name='reglamentos',
            name='archivo',
            field=models.FileField(upload_to='static/files/reglamentos/'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/tramites/'),
        ),
    ]
