# Generated by Django 5.2.3 on 2025-07-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_archivotramite_archivo_alter_club_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivotramite',
            name='archivo',
            field=models.FileField(upload_to='tramites/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubes/'),
        ),
        migrations.AlterField(
            model_name='fotohistoriaraza',
            name='imagen',
            field=models.ImageField(upload_to='historia_razas/'),
        ),
        migrations.AlterField(
            model_name='historiarazas',
            name='imagenPrincipal',
            field=models.ImageField(blank=True, null=True, upload_to='historia_razas/'),
        ),
        migrations.AlterField(
            model_name='juez',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/'),
        ),
        migrations.AlterField(
            model_name='juez',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='jueces/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='rankings/'),
        ),
        migrations.AlterField(
            model_name='reglamentos',
            name='archivo',
            field=models.FileField(upload_to='reglamentos/'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tramites/'),
        ),
    ]
