# Generated by Django 5.2.3 on 2025-07-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_archivotramite_archivo_alter_club_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_categoria', models.CharField(help_text='Código único para identificar la categoría', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Noticias',
                'verbose_name_plural': 'Categorías de Noticias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='noticias',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='core.categorianoticias'),
        ),
    ]
