# Generated by Django 5.2.3 on 2025-07-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_categorianoticias_alter_noticias_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='categoria',
        ),
        migrations.AddField(
            model_name='noticias',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='noticias', to='core.categorianoticias'),
        ),
    ]
