# Generated by Django 5.2.3 on 2025-07-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_noticias_categoria_noticias_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorianoticias',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categorianoticias',
            name='codigo_categoria',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
