# Generated by Django 5.2.3 on 2025-08-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_categorianoticias_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorianoticias',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Sin color'), ('#e35454', 'Rojo'), ('#f17a4a', 'Naranja'), ('#e6c34d', 'Amarillo'), ('#f0a754', 'Ámbar'), ('#5b9bd5', 'Azul'), ('#70ad47', 'Verde'), ('#9e7bb5', 'Morado'), ('#4bc0c0', 'Turquesa'), ('#9e9e9e', 'Gris')], help_text='Selecciona un color cálido para la categoría', max_length=7, null=True),
        ),
    ]
